version: "3.7"

services:
  # Core configuration
  php-fpm:
    container_name: ${CONTAINER_NAME}_php-fpm
    build:
      args:
        WORKFOLDER: "${WORKFOLDER}"
      context: './docker/php/'
      target: base
    ports:
      - '${PHP_PORT}:9000'
    volumes:
      - './:${WORKFOLDER}:rw'
      - './docker/php/php.ini:/usr/local/etc/php/php.ini'
    restart: always

  nginx:
    container_name: ${CONTAINER_NAME}_nginx
    image: nginx:latest
    ports:
      - '${NGINX_PORT}:80'
    links:
      - php-fpm
    volumes:
      - './:${WORKFOLDER}:rw'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './docker/nginx/logs/:/var/log/nginx'
    restart: always

  mysql:
    container_name: ${CONTAINER_NAME}_mysql
    image: mysql:5.7
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_DATABASE: '${MYSQL_DBNAME}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - 'mysql:/var/lib/mysql'
    restart: always

  adminer:
    container_name: ${CONTAINER_NAME}_adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - '${ADMINER_PORT}:8080'

volumes:
  mysql:
